var labels = {

en : {
//english labels go here
about_mixeek : "About Mixeek",
about : "About",
get_inspiration : "Get Inspiration",
examples : "Examples",
contact_us : "Contact Us",
contact : "Contact",
request_feature : "Request Feature",
do_you_miss_anything : "Do you miss any feature? Tell us.",
publish_title : "Publish your work on Mixeek website",
publish : "Publish",
file_menu : "File Menu",
file : "File",
download_engine : "Download Engine",
download_title : "Download Mixeek JavaScript ready-to-use package",
visit_documentation : "Visit Documentation",
help : "Help",
canvas : "Canvas",
size : "Size",
w : "W",
h : "H",
allow_overflow : "Allow Overflow",
background : "Background",
color : "Color",
upload_canvas : "Upload your image as a background for the canvas",
load : "Load",
repeat : "Repeat",
x : "X",
y : "Y",
frame : "Frame",
position : "Position",
z_index : "Z Index",
scale_and_rotation : "Scale and Rotation",
s : "S",
r : "R",
opacity : "Opacity",
o : "O",
sprites : "Sprites",
image_index : "Image index",
interpolation : "Interpolation",
linear : "linear",
bezier_title : "Comming soon! ..REVOLUTIONARY curve based position interpolation, converts polyline trajectory to ideal curve",
bezier : "bezier",
easing : "Easing",
ease : "ease",
in : "in",
out : "out",
in_out : "in-out",
action : "Action",
layer_val : "layer",
frame_val : "frame",
copy : "Copy",
undo : "Undo",
redo : "Redo",
delete : "Delete",
layers : "Layers",
add_layer : "Add Layer",
layer_properties : "Layer Properties",
upload_layer : "Upload your image as a background for the layer",
sprite_count : "sprite count",
sprite_count_title : "The number of sprite images included. Vertical sprite composition is required.",
parent : "Parent",
ok : "OK",
timeline : "Timeline",
time : "Time",
duration : "Duration",
from : "From", 
to : "To",
playback_mode : "Playback mode. Toggle between HTML5 Canvas, CSS3 animation and pure JavaScript",
save : "Save",
open : "Open",
export_source : "Export Source",
save_animation : "Save animation for later reopening",
open_existing_animation : "Open existing animation",
export_animation : "Export animation sources for use in your website",
sprite : "Sprite",
down: "down",
up : "up"
},

es : {
//espanol labels go here
about_mixeek : "Acerca de Mixeek",
about : "Acerca de",
get_inspiration : "Buscar inspiración",
examples : "Ejemplos",
contact_us : "Contacto",
contact : "Contacto",
request_feature : "Solicitar una Característica",
do_you_miss_anything : "¿Echas de menos alguna de las funciones? Cuéntenos.",
publish_title : "Publicar su trabajo en el sitio web de Mixeek",
publish : "Publicar",
file_menu : "Menú Archivo",
file : "Archivo",
download_engine : "Descargar motor",
download_title : "Descargar el paquete JavaScript de Mixeek listo para usar",
visit_documentation : "Explorar la documentación",
help : "Ayuda",
canvas : "Escenario",
size : "Tamaño",
w : "An",
h : "Al",
allow_overflow : "Permitir desbordamiento",
background : "Fondo",
color : "Color",
upload_canvas : "Subir una imagen de fondo para el escenario",
load : "Subir",
repeat : "Repetición",
x : "X",
y : "Y",
frame : "Fotograma",
position : "Posición",
z_index : "Índice Z",
scale_and_rotation : "Escala y rotación",
s : "Es",
r : "Ro",
opacity : "Opacidad",
o : "O",
sprites : "Actores",
image_index : "Índice de imagen",
interpolation : "Interpolación",
linear : "lineal",
bezier_title : "¡Muy pronto! ..REVOLUCIONARIA interpolación basada en la posición sobre una curva, que convierte una trayectoria segmentada en una curva suave",
bezier : "bézier",
easing : "Aceleración",
ease : "amortiguado",
in : "acelerado",
out : "frenado",
in_out : "dentro-fuera",
action : "Acción",
layer_val : "capa",
frame_val : "fotograma",
copy : "Copiar",
undo : "Deshacer",
redo : "Rehacer",
delete : "Borrar",
layers : "Capas",
add_layer : "Añadir capa",
layer_properties : "Propiedades de capa",
upload_layer : "Subir una imagen de fondo para la capa",
sprite_count : "imágenes del actor",
sprite_count_title : "El número de imágenes que componen el actor. La composición de estas imágenes debe ser vertical.",
parent : "Padre",
ok : "Aceptar",
timeline : "Línea de tiempo",
time : "Tiempo",
duration : "Duración",
from : "Desde", 
to : "Hasta",
playback_mode : "Modo de reproducción. Alterna entre canvas de HTML5, animación CSS y JavaScript puro",
save : "Guardar",
open : "Abrir",
export_source : "Exportar codigo fuente",
save_animation : "Guardar la animación para reabrirla posteriormente",
open_existing_animation : "Abrir una animación previamente guardada",
export_animation : "Exportar el código necesario para incrustar la animación en una página web",
sprite : "Capa",
down: "abajo",
up : "arriba"
},

it : {
//italian labels go here
},

fr : {
//french labels go here
},

de : {
//deutch labels go here
}

};
